/****************************************************************************
**
** Metadata for PERCo_S20_SDK generated by dumpcpp v5.11.2 using
** dumpcpp C:\\libs\PERCo.tlb -o C:\\fff.html
** from the type library C:\\libs\PERCo.tlb
**
****************************************************************************/

#define QAX_DUMPCPP_PERCO_S20_SDK_NOINLINES
#include "PERCo.h"

using namespace PERCo_S20_SDK;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[53];
    char stringdata0[649];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 28, 0),
QT_MOC_LITERAL(1, 29, 9, 0),
QT_MOC_LITERAL(2, 39, 0, 0),
QT_MOC_LITERAL(3, 40, 4, 0),
QT_MOC_LITERAL(4, 45, 6, 0),
QT_MOC_LITERAL(5, 52, 4, 0),
QT_MOC_LITERAL(6, 57, 4, 0),
QT_MOC_LITERAL(7, 62, 15, 0),
QT_MOC_LITERAL(8, 78, 4, 0),
QT_MOC_LITERAL(9, 83, 6, 0),
QT_MOC_LITERAL(10, 90, 4, 0),
QT_MOC_LITERAL(11, 95, 4, 0),
QT_MOC_LITERAL(12, 100, 13, 0),
QT_MOC_LITERAL(13, 114, 10, 0),
QT_MOC_LITERAL(14, 125, 5, 0),
QT_MOC_LITERAL(15, 131, 20, 0),
QT_MOC_LITERAL(16, 152, 12, 0),
QT_MOC_LITERAL(17, 165, 8, 0),
QT_MOC_LITERAL(18, 174, 10, 0),
QT_MOC_LITERAL(19, 185, 11, 0),
QT_MOC_LITERAL(20, 197, 10, 0),
QT_MOC_LITERAL(21, 208, 24, 0),
QT_MOC_LITERAL(22, 233, 14, 0),
QT_MOC_LITERAL(23, 248, 7, 0),
QT_MOC_LITERAL(24, 256, 16, 0),
QT_MOC_LITERAL(25, 273, 19, 0),
QT_MOC_LITERAL(26, 293, 6, 0),
QT_MOC_LITERAL(27, 300, 9, 0),
QT_MOC_LITERAL(28, 310, 23, 0),
QT_MOC_LITERAL(29, 334, 15, 0),
QT_MOC_LITERAL(30, 350, 12, 0),
QT_MOC_LITERAL(31, 363, 7, 0),
QT_MOC_LITERAL(32, 371, 5, 0),
QT_MOC_LITERAL(33, 377, 5, 0),
QT_MOC_LITERAL(34, 383, 6, 0),
QT_MOC_LITERAL(35, 390, 11, 0),
QT_MOC_LITERAL(36, 402, 8, 0),
QT_MOC_LITERAL(37, 411, 10, 0),
QT_MOC_LITERAL(38, 422, 5, 0),
QT_MOC_LITERAL(39, 428, 6, 0),
QT_MOC_LITERAL(40, 435, 9, 0),
QT_MOC_LITERAL(41, 445, 12, 0),
QT_MOC_LITERAL(42, 458, 18, 0),
QT_MOC_LITERAL(43, 477, 10, 0),
QT_MOC_LITERAL(44, 488, 15, 0),
QT_MOC_LITERAL(45, 504, 7, 0),
QT_MOC_LITERAL(46, 512, 29, 0),
QT_MOC_LITERAL(47, 542, 11, 0),
QT_MOC_LITERAL(48, 554, 13, 0),
QT_MOC_LITERAL(49, 568, 28, 0),
QT_MOC_LITERAL(50, 597, 6, 0),
QT_MOC_LITERAL(51, 604, 29, 0),
QT_MOC_LITERAL(52, 634, 13, 0)
    },
    "PERCo_S20_SDK::IExchangeMain\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0Append_Access\0IDispatch*\0AData\0CheckSynchronization\0"
    "CheckVersion\0QString&\0AVersionDB\0AVersionDll\0DisConnect\0ExecuteAccessCardsAction\0"
    "ExecuteCommand\0GetData\0GetDataForReport\0GetErrorDescription\0AErorr\0GetEvents\0"
    "GetGlobalReaderProtocol\0GetInternalInfo\0GetOneEmploy\0GetUser\0AUser\0APort\0"
    "APassw\0ReloadCache\0SendData\0SetConnect\0AHost\0ALogin\0APassword\0SetConnectEx\0"
    "TestGenerateEvents\0UpdateData\0Withdraw_Access\0control\0PERCo_S20_SDK::CoExchangeMain\0"
    "Interface 0\0IExchangeMain\0PERCo_S20_SDK::IPERCoS20_SDK\0AError\0"
    "PERCo_S20_SDK::coPERCoS20_SDK\0IPERCoS20_SDK\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_PERCo_S20_SDK__IExchangeMain[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    24, 14, // methods
    1, 222, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 134, 2, 5,
    7, 1, 143, 2, 5,
    9, 3, 146, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 153, 2, 9,
    15, 0, 156, 2, 9,
    16, 2, 157, 2, 9,
    20, 0, 162, 2, 9,
    21, 1, 163, 2, 9,
    22, 1, 166, 2, 9,
    23, 1, 169, 2, 9,
    24, 1, 172, 2, 9,
    25, 1, 175, 2, 9,
    27, 1, 178, 2, 9,
    28, 1, 181, 2, 9,
    29, 0, 184, 2, 9,
    30, 1, 185, 2, 9,
    31, 3, 188, 2, 9,
    35, 1, 195, 2, 9,
    36, 1, 198, 2, 9,
    37, 4, 201, 2, 9,
    41, 1, 210, 2, 9,
    42, 1, 213, 2, 9,
    43, 1, 216, 2, 9,
    44, 1, 219, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 26,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 0x80000000 | 17, 32, 33, 34,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 38, 33, 39, 40,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,

 // properties: name, type, flags
    45, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IExchangeMain::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_PERCo_S20_SDK__IExchangeMain, 0, 0, 0 }
};

void *IExchangeMain::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "PERCo_S20_SDK::IExchangeMain"))
        return static_cast<void*>(const_cast<IExchangeMain*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_PERCo_S20_SDK__CoExchangeMain[] = {

 // content:
    7, // revision
    46,  // classname
    1, 14, // classinfo
    24, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    47, 48, 

// signal: name, argc, parameters, tag, flags
    1, 4, 136, 2, 5,
    7, 1, 145, 2, 5,
    9, 3, 148, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 155, 2, 9,
    15, 0, 158, 2, 9,
    16, 2, 159, 2, 9,
    20, 0, 164, 2, 9,
    21, 1, 165, 2, 9,
    22, 1, 168, 2, 9,
    23, 1, 171, 2, 9,
    24, 1, 174, 2, 9,
    25, 1, 177, 2, 9,
    27, 1, 180, 2, 9,
    28, 1, 183, 2, 9,
    29, 0, 186, 2, 9,
    30, 1, 187, 2, 9,
    31, 3, 190, 2, 9,
    35, 1, 197, 2, 9,
    36, 1, 200, 2, 9,
    37, 4, 203, 2, 9,
    41, 1, 212, 2, 9,
    42, 1, 215, 2, 9,
    43, 1, 218, 2, 9,
    44, 1, 221, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 26,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 0x80000000 | 17, 32, 33, 34,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 38, 33, 39, 40,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,

    0 // eod
};

const QMetaObject CoExchangeMain::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_PERCo_S20_SDK__CoExchangeMain, 0, 0, 0 }
};

void *CoExchangeMain::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "PERCo_S20_SDK::CoExchangeMain"))
        return static_cast<void*>(const_cast<CoExchangeMain*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_PERCo_S20_SDK__IPERCoS20_SDK[] = {

 // content:
    7, // revision
    49,  // classname
    0, 0, // classinfo
    24, 14, // methods
    1, 222, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 134, 2, 5,
    7, 1, 143, 2, 5,
    9, 3, 146, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 153, 2, 9,
    15, 0, 156, 2, 9,
    16, 2, 157, 2, 9,
    20, 0, 162, 2, 9,
    21, 1, 163, 2, 9,
    22, 1, 166, 2, 9,
    23, 1, 169, 2, 9,
    24, 1, 172, 2, 9,
    25, 1, 175, 2, 9,
    27, 1, 178, 2, 9,
    28, 1, 181, 2, 9,
    29, 0, 184, 2, 9,
    30, 1, 185, 2, 9,
    31, 3, 188, 2, 9,
    35, 1, 195, 2, 9,
    36, 1, 198, 2, 9,
    37, 4, 201, 2, 9,
    41, 1, 210, 2, 9,
    42, 1, 213, 2, 9,
    43, 1, 216, 2, 9,
    44, 1, 219, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 50,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 0x80000000 | 17, 32, 33, 34,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 38, 33, 39, 40,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,

 // properties: name, type, flags
    45, QMetaType::QString, 0x0a055003, 		 // QString control

    0 // eod
};

const QMetaObject IPERCoS20_SDK::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_PERCo_S20_SDK__IPERCoS20_SDK, 0, 0, 0 }
};

void *IPERCoS20_SDK::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "PERCo_S20_SDK::IPERCoS20_SDK"))
        return static_cast<void*>(const_cast<IPERCoS20_SDK*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_PERCo_S20_SDK__coPERCoS20_SDK[] = {

 // content:
    7, // revision
    51,  // classname
    1, 14, // classinfo
    24, 16, // methods
    0, 0, // properties
    0, 0, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

 // classinfo: key, value
    47, 52, 

// signal: name, argc, parameters, tag, flags
    1, 4, 136, 2, 5,
    7, 1, 145, 2, 5,
    9, 3, 148, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 1, 155, 2, 9,
    15, 0, 158, 2, 9,
    16, 2, 159, 2, 9,
    20, 0, 164, 2, 9,
    21, 1, 165, 2, 9,
    22, 1, 168, 2, 9,
    23, 1, 171, 2, 9,
    24, 1, 174, 2, 9,
    25, 1, 177, 2, 9,
    27, 1, 180, 2, 9,
    28, 1, 183, 2, 9,
    29, 0, 186, 2, 9,
    30, 1, 187, 2, 9,
    31, 3, 190, 2, 9,
    35, 1, 197, 2, 9,
    36, 1, 200, 2, 9,
    37, 4, 203, 2, 9,
    41, 1, 212, 2, 9,
    42, 1, 215, 2, 9,
    43, 1, 218, 2, 9,
    44, 1, 221, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 17, 0x80000000 | 17, 18, 19,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 50,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, 0x80000000 | 17, 32, 33, 34,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, QMetaType::QString, 38, 33, 39, 40,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,
    QMetaType::Int, 0x80000000 | 13, 14,

    0 // eod
};

const QMetaObject coPERCoS20_SDK::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_PERCo_S20_SDK__coPERCoS20_SDK, 0, 0, 0 }
};

void *coPERCoS20_SDK::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "PERCo_S20_SDK::coPERCoS20_SDK"))
        return static_cast<void*>(const_cast<coPERCoS20_SDK*>(this));
    return QAxObject::qt_metacast(_clname);
}

