/****************************************************************************
**
** Namespace PERCo_S20_SDK generated by dumpcpp v5.11.2 using
** dumpcpp C:\\libs\PERCo.tlb -o C:\\fff.html
** from the type library C:\\libs\PERCo.tlb
**
****************************************************************************/

#pragma once

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef PERCO_S20_SDK_EXPORT
#define PERCO_S20_SDK_EXPORT
#endif

#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>

struct IDispatch;


// Referenced namespace

namespace PERCo_S20_SDK {


class PERCO_S20_SDK_EXPORT IExchangeMain : public QAxObject
{
public:
    IExchangeMain(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method Append_Access
    */
    inline int Append_Access(IDispatch* AData);

    /*
    Method CheckSynchronization
    */
    inline int CheckSynchronization();

    /*
    Method CheckVersion
    */
    inline int CheckVersion(QString& AVersionDB, QString& AVersionDll);

    /*
    Method DisConnect
    */
    inline int DisConnect();

    /*
    Method ExecuteAccessCardsAction
    */
    inline int ExecuteAccessCardsAction(IDispatch* AData);

    /*
    Method ExecuteCommand
    */
    inline int ExecuteCommand(IDispatch* AData);

    /*
    Method GetData
    */
    inline int GetData(IDispatch* AData);

    /*
    Method GetDataForReport
    */
    inline int GetDataForReport(IDispatch* AData);

    /*
    Method GetErrorDescription
    */
    inline int GetErrorDescription(IDispatch* AErorr);

    /*
    Method GetEvents
    */
    inline int GetEvents(IDispatch* AData);

    /*
    Method GetGlobalReaderProtocol
    */
    inline int GetGlobalReaderProtocol(IDispatch* AData);

    /*
    Method GetInternalInfo
    */
    inline int GetInternalInfo();

    /*
    Method GetOneEmploy
    */
    inline int GetOneEmploy(IDispatch* AData);

    /*
    Method GetUser
    */
    inline int GetUser(const QString& AUser, const QString& APort, QString& APassw);

    /*
    Method ReloadCache
    */
    inline int ReloadCache(IDispatch* AData);

    /*
    Method SendData
    */
    inline int SendData(IDispatch* AData);

    /*
    Method SetConnect
    */
    inline int SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword);

    /*
    Method SetConnectEx
    */
    inline int SetConnectEx(IDispatch* AData);

    /*
    Method TestGenerateEvents
    */
    inline int TestGenerateEvents(IDispatch* AData);

    /*
    Method UpdateData
    */
    inline int UpdateData(IDispatch* AData);

    /*
    Method Withdraw_Access
    */
    inline int Withdraw_Access(IDispatch* AData);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class PERCO_S20_SDK_EXPORT IPERCoS20_SDK : public QAxObject
{
public:
    IPERCoS20_SDK(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Method Append_Access
    */
    inline int Append_Access(IDispatch* AData);

    /*
    Method CheckSynchronization
    */
    inline int CheckSynchronization();

    /*
    Method CheckVersion
    */
    inline int CheckVersion(QString& AVersionDB, QString& AVersionDll);

    /*
    Method DisConnect
    */
    inline int DisConnect();

    /*
    Method ExecuteAccessCardsAction
    */
    inline int ExecuteAccessCardsAction(IDispatch* AData);

    /*
    Method ExecuteCommand
    */
    inline int ExecuteCommand(IDispatch* AData);

    /*
    Method GetData
    */
    inline int GetData(IDispatch* AData);

    /*
    Method GetDataForReport
    */
    inline int GetDataForReport(IDispatch* AData);

    /*
    Method GetErrorDescription
    */
    inline int GetErrorDescription(IDispatch* AError);

    /*
    Method GetEvents
    */
    inline int GetEvents(IDispatch* AData);

    /*
    Method GetGlobalReaderProtocol
    */
    inline int GetGlobalReaderProtocol(IDispatch* AData);

    /*
    Method GetInternalInfo
    */
    inline int GetInternalInfo();

    /*
    Method GetOneEmploy
    */
    inline int GetOneEmploy(IDispatch* AData);

    /*
    Method GetUser
    */
    inline int GetUser(const QString& AUser, const QString& APort, QString& APassw);

    /*
    Method ReloadCache
    */
    inline int ReloadCache(IDispatch* AData);

    /*
    Method SendData
    */
    inline int SendData(IDispatch* AData);

    /*
    Method SetConnect
    */
    inline int SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword);

    /*
    Method SetConnectEx
    */
    inline int SetConnectEx(IDispatch* AData);

    /*
    Method TestGenerateEvents
    */
    inline int TestGenerateEvents(IDispatch* AData);

    /*
    Method UpdateData
    */
    inline int UpdateData(IDispatch* AData);

    /*
    Method Withdraw_Access
    */
    inline int Withdraw_Access(IDispatch* AData);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// Actual coclasses
class PERCO_S20_SDK_EXPORT CoExchangeMain : public QAxObject
{
public:
    CoExchangeMain(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl(QStringLiteral("{e74fa501-350f-43cf-8c15-d831778fd465}"));
    }

    CoExchangeMain(IExchangeMain *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method Append_Access
    */
    inline int Append_Access(IDispatch* AData);

    /*
    Method CheckSynchronization
    */
    inline int CheckSynchronization();

    /*
    Method CheckVersion
    */
    inline int CheckVersion(QString& AVersionDB, QString& AVersionDll);

    /*
    Method DisConnect
    */
    inline int DisConnect();

    /*
    Method ExecuteAccessCardsAction
    */
    inline int ExecuteAccessCardsAction(IDispatch* AData);

    /*
    Method ExecuteCommand
    */
    inline int ExecuteCommand(IDispatch* AData);

    /*
    Method GetData
    */
    inline int GetData(IDispatch* AData);

    /*
    Method GetDataForReport
    */
    inline int GetDataForReport(IDispatch* AData);

    /*
    Method GetErrorDescription
    */
    inline int GetErrorDescription(IDispatch* AErorr);

    /*
    Method GetEvents
    */
    inline int GetEvents(IDispatch* AData);

    /*
    Method GetGlobalReaderProtocol
    */
    inline int GetGlobalReaderProtocol(IDispatch* AData);

    /*
    Method GetInternalInfo
    */
    inline int GetInternalInfo();

    /*
    Method GetOneEmploy
    */
    inline int GetOneEmploy(IDispatch* AData);

    /*
    Method GetUser
    */
    inline int GetUser(const QString& AUser, const QString& APort, QString& APassw);

    /*
    Method ReloadCache
    */
    inline int ReloadCache(IDispatch* AData);

    /*
    Method SendData
    */
    inline int SendData(IDispatch* AData);

    /*
    Method SetConnect
    */
    inline int SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword);

    /*
    Method SetConnectEx
    */
    inline int SetConnectEx(IDispatch* AData);

    /*
    Method TestGenerateEvents
    */
    inline int TestGenerateEvents(IDispatch* AData);

    /*
    Method UpdateData
    */
    inline int UpdateData(IDispatch* AData);

    /*
    Method Withdraw_Access
    */
    inline int Withdraw_Access(IDispatch* AData);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

class PERCO_S20_SDK_EXPORT coPERCoS20_SDK : public QAxObject
{
public:
    coPERCoS20_SDK(QObject *parent = 0)
    : QAxObject(parent)
    {
        setControl(QStringLiteral("{489eb0b2-5171-436d-8756-11e42e689b2d}"));
    }

    coPERCoS20_SDK(IPERCoS20_SDK *iface)
    : QAxObject()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Method Append_Access
    */
    inline int Append_Access(IDispatch* AData);

    /*
    Method CheckSynchronization
    */
    inline int CheckSynchronization();

    /*
    Method CheckVersion
    */
    inline int CheckVersion(QString& AVersionDB, QString& AVersionDll);

    /*
    Method DisConnect
    */
    inline int DisConnect();

    /*
    Method ExecuteAccessCardsAction
    */
    inline int ExecuteAccessCardsAction(IDispatch* AData);

    /*
    Method ExecuteCommand
    */
    inline int ExecuteCommand(IDispatch* AData);

    /*
    Method GetData
    */
    inline int GetData(IDispatch* AData);

    /*
    Method GetDataForReport
    */
    inline int GetDataForReport(IDispatch* AData);

    /*
    Method GetErrorDescription
    */
    inline int GetErrorDescription(IDispatch* AError);

    /*
    Method GetEvents
    */
    inline int GetEvents(IDispatch* AData);

    /*
    Method GetGlobalReaderProtocol
    */
    inline int GetGlobalReaderProtocol(IDispatch* AData);

    /*
    Method GetInternalInfo
    */
    inline int GetInternalInfo();

    /*
    Method GetOneEmploy
    */
    inline int GetOneEmploy(IDispatch* AData);

    /*
    Method GetUser
    */
    inline int GetUser(const QString& AUser, const QString& APort, QString& APassw);

    /*
    Method ReloadCache
    */
    inline int ReloadCache(IDispatch* AData);

    /*
    Method SendData
    */
    inline int SendData(IDispatch* AData);

    /*
    Method SetConnect
    */
    inline int SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword);

    /*
    Method SetConnectEx
    */
    inline int SetConnectEx(IDispatch* AData);

    /*
    Method TestGenerateEvents
    */
    inline int TestGenerateEvents(IDispatch* AData);

    /*
    Method UpdateData
    */
    inline int UpdateData(IDispatch* AData);

    /*
    Method Withdraw_Access
    */
    inline int Withdraw_Access(IDispatch* AData);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_PERCO_S20_SDK_NOINLINES
inline int IExchangeMain::Append_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int IExchangeMain::CheckSynchronization()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int IExchangeMain::CheckVersion(QString& AVersionDB, QString& AVersionDll)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AVersionDB, (void*)&AVersionDll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int IExchangeMain::DisConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int IExchangeMain::ExecuteAccessCardsAction(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int IExchangeMain::ExecuteCommand(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int IExchangeMain::GetData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int IExchangeMain::GetDataForReport(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int IExchangeMain::GetErrorDescription(IDispatch* AErorr)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AErorr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int IExchangeMain::GetEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int IExchangeMain::GetGlobalReaderProtocol(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int IExchangeMain::GetInternalInfo()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int IExchangeMain::GetOneEmploy(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int IExchangeMain::GetUser(const QString& AUser, const QString& APort, QString& APassw)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AUser, (void*)&APort, (void*)&APassw};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int IExchangeMain::ReloadCache(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int IExchangeMain::SendData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int IExchangeMain::SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AHost, (void*)&APort, (void*)&ALogin, (void*)&APassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int IExchangeMain::SetConnectEx(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int IExchangeMain::TestGenerateEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline int IExchangeMain::UpdateData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline int IExchangeMain::Withdraw_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}


inline int CoExchangeMain::Append_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int CoExchangeMain::CheckSynchronization()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int CoExchangeMain::CheckVersion(QString& AVersionDB, QString& AVersionDll)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AVersionDB, (void*)&AVersionDll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int CoExchangeMain::DisConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int CoExchangeMain::ExecuteAccessCardsAction(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int CoExchangeMain::ExecuteCommand(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int CoExchangeMain::GetData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int CoExchangeMain::GetDataForReport(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int CoExchangeMain::GetErrorDescription(IDispatch* AErorr)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AErorr};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int CoExchangeMain::GetEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int CoExchangeMain::GetGlobalReaderProtocol(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int CoExchangeMain::GetInternalInfo()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int CoExchangeMain::GetOneEmploy(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int CoExchangeMain::GetUser(const QString& AUser, const QString& APort, QString& APassw)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AUser, (void*)&APort, (void*)&APassw};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int CoExchangeMain::ReloadCache(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int CoExchangeMain::SendData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int CoExchangeMain::SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AHost, (void*)&APort, (void*)&ALogin, (void*)&APassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int CoExchangeMain::SetConnectEx(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int CoExchangeMain::TestGenerateEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline int CoExchangeMain::UpdateData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline int CoExchangeMain::Withdraw_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}


inline int IPERCoS20_SDK::Append_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::CheckSynchronization()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::CheckVersion(QString& AVersionDB, QString& AVersionDll)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AVersionDB, (void*)&AVersionDll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::DisConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::ExecuteAccessCardsAction(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::ExecuteCommand(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetDataForReport(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetErrorDescription(IDispatch* AError)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AError};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetGlobalReaderProtocol(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetInternalInfo()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetOneEmploy(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::GetUser(const QString& AUser, const QString& APort, QString& APassw)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AUser, (void*)&APort, (void*)&APassw};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::ReloadCache(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::SendData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AHost, (void*)&APort, (void*)&ALogin, (void*)&APassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::SetConnectEx(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::TestGenerateEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::UpdateData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline int IPERCoS20_SDK::Withdraw_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}


inline int coPERCoS20_SDK::Append_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::CheckSynchronization()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::CheckVersion(QString& AVersionDB, QString& AVersionDll)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AVersionDB, (void*)&AVersionDll};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::DisConnect()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::ExecuteAccessCardsAction(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::ExecuteCommand(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetDataForReport(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetErrorDescription(IDispatch* AError)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AError};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetGlobalReaderProtocol(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetInternalInfo()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 19, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetOneEmploy(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 20, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::GetUser(const QString& AUser, const QString& APort, QString& APassw)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AUser, (void*)&APort, (void*)&APassw};
    qt_metacall(QMetaObject::InvokeMetaMethod, 21, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::ReloadCache(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 22, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::SendData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 23, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::SetConnect(const QString& AHost, const QString& APort, const QString& ALogin, const QString& APassword)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AHost, (void*)&APort, (void*)&ALogin, (void*)&APassword};
    qt_metacall(QMetaObject::InvokeMetaMethod, 24, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::SetConnectEx(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 25, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::TestGenerateEvents(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 26, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::UpdateData(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 27, _a);
    return qax_result;
}

inline int coPERCoS20_SDK::Withdraw_Access(IDispatch* AData)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&AData};
    qt_metacall(QMetaObject::InvokeMetaMethod, 28, _a);
    return qax_result;
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<PERCo_S20_SDK::IExchangeMain, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<PERCo_S20_SDK::IExchangeMain*>(t)->PERCo_S20_SDK::IExchangeMain::~IExchangeMain();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) PERCo_S20_SDK::IExchangeMain;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const PERCo_S20_SDK::IExchangeMain*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<PERCo_S20_SDK::IExchangeMain*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<PERCo_S20_SDK::CoExchangeMain, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<PERCo_S20_SDK::CoExchangeMain*>(t)->PERCo_S20_SDK::CoExchangeMain::~CoExchangeMain();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) PERCo_S20_SDK::CoExchangeMain;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const PERCo_S20_SDK::CoExchangeMain*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<PERCo_S20_SDK::CoExchangeMain*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<PERCo_S20_SDK::IPERCoS20_SDK, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<PERCo_S20_SDK::IPERCoS20_SDK*>(t)->PERCo_S20_SDK::IPERCoS20_SDK::~IPERCoS20_SDK();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) PERCo_S20_SDK::IPERCoS20_SDK;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const PERCo_S20_SDK::IPERCoS20_SDK*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<PERCo_S20_SDK::IPERCoS20_SDK*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<PERCo_S20_SDK::coPERCoS20_SDK, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<PERCo_S20_SDK::coPERCoS20_SDK*>(t)->PERCo_S20_SDK::coPERCoS20_SDK::~coPERCoS20_SDK();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) PERCo_S20_SDK::coPERCoS20_SDK;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const PERCo_S20_SDK::coPERCoS20_SDK*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<PERCo_S20_SDK::coPERCoS20_SDK*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE


